// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/**
 * Let the UI load even when Netlify env vars are missing.
 * Auth and database actions still require real values in Netlify.
 */
const hasSupabaseEnv = Boolean(envUrl && envKey);

if (!hasSupabaseEnv) {
  console.warn(
    'Supabase env vars are missing. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Netlify.'
  );
}

const SUPABASE_URL = envUrl || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = envKey || 'placeholder-publishable-key';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export { hasSupabaseEnv };
